micronaut:
  application:
    name: demoKt
  server:
    port: 7701
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
datasources:
    default:
      url: jdbc:mysql://localhost:3306/todo?useSSL=false&serverTimezone=UTC
      driverClassName: com.mysql.cj.jdbc.Driver
      username: root
      password: 987654
      dialect: MYSQL